# Generated by Django 6.0.2 on 2026-02-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=15),
        ),
    ]
