# Generated by Django 5.2.6 on 2026-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_pic_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='occupation_type',
            field=models.CharField(default='salary', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
