# Generated by Django 5.2.6 on 2026-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_occupation_type_customuser_other_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expenses_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
