# Generated by Django 5.2.6 on 2026-02-18 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('book_profit', 'Book Profit/Loss')], max_length=20)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('index', 'Index Fund')], default='stock', max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of transaction', max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='quantity × price', max_digits=15)),
                ('realized_pl', models.DecimalField(blank=True, decimal_places=2, help_text='Realized P/L for sell/book transactions', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
