# Generated by Django 5.2.6 on 2026-02-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
