# Generated by Django 5.2.6 on 2026-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_holding_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency')], default='stock', max_length=10),
        ),
    ]
