# Generated by Django 5.2.6 on 2026-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_holding_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('index', 'Index Fund')], default='stock', max_length=10),
        ),
    ]
