# Generated by Django 6.0.2 on 2026-03-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_holding_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='position_type',
            field=models.CharField(choices=[('long', 'Long (Buy)'), ('short', 'Short (Sell)')], default='long', max_length=10),
        ),
    ]
